### ISSUE TITLE
Welcome Cog changes

### ISSUE THREAD

**Issue by irdumbs** [irdumbs/Dumb-Cogs#3]
- [x] Adding randomized greetings
- [ ] Fix missing channels/servers bugs
- [ ] Add roles on join

**Comment by irdumbs** [comment]
missing channels should be fixed

**Comment by Twentysix26** [comment]
- [x] Add welcome cog to master

**Comment by Kowlin** [comment]
TBH, I think you can atleast PR it over to master, I think we can both handle the bugfixes required if there are any needed.

**Comment by Chovin** [comment]
aikaterna commented on Nov 22, 2016 • edited [red-cogs#36](https://github.com/Twentysix26/Red-Cogs/pull/57)  
[p]welcomeset msg list only returns non-bot welcomes in the list.
*May want to include bot welcome messages under [p]welcomeset bot list
*May also not be relevant until there's more than one bot welcome message, like the random queue on user welcome messages.

[p]welcomeset bot role with no argument returns `Error in command 'welcomeset bot role' - AttributeError: 'NoneType' object has no attribute 'name'`

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\message_economy.py", line 59, in process_message
    server = message.server.id
AttributeError: 'NoneType' object has no attribute 'id'
```  

In the [p]welcomeset bot role [role] help, you may want to add that you need to encapsulate roles with spaces within double quotes.

From a user standpoint, it still has the issue where a bot can't add a bot to it's same permission level - that you mentioned in your first post.

**Comment by Chovin** [comment]
- [x] won't list bot msgs until they are also random
- [ ] welcomeset bot role w/out args -> error
- [ ] help welcomeset bot role -> enclose multiword with spaces
- [ ] check permissions. May not do this yet
- [ ] make whispers a server owner only command (not ever bot owner)
